### ISSUE TITLE
Server Out of Date?

### ISSUE THREAD

**Issue by TwistedTail** [nedhyett/Vermilion#104]
Client "TwistedTail" connected
[Vermilion2 - Server] [Notification:TransBroadcast] TwistedTail left the server: Server out of date
Dropped TwistedTail from server (Server out of date)

[Vermilion 2] lua/vermilion2/modules/spawn_settings/init.lua:101: Tryed to use a NULL entity!
     1. SetStepSize - [C]:-1
      2. ApplyFunc - lua/vermilion2/modules/spawn_settings/init.lua:101
       3. unkkown - lua/vermilion2/modules/spawn_settings/init.lua:140

Timer Failed! [Simple][@lua/vermilion2/modules/spawn_settings/init.lua (line 138)]

[Vermilion 2] lua/vermilion2/config.lua:691: tryed to use a NULL entity!
    1. GetName - [C]:-1
     2. unknown - lua/vermilion2/config.lua:691

Timer Failed! [Simple][@lua/vermilion2/config.lua (line 686)]

The server is up to date, updated two time and this error keeps showing in the console and it keeps kicking me.

**Comment by TwistedTail** [comment]
http://prntscr.com/6smsi1

**Comment by nedhyett** [comment]
Have you tried verifying the server files using SteamCMD or are you using the dev branch of GMod? I don't do anything that could cause the server to say "Server out of date".

Although, it does present an interesting bug in the configuration whereby it errors if someone leaves before the management engine has registered them as an active player...

**Comment by TwistedTail** [comment]
Checked and updated everything.
I don't even know there was a Dev Branch.

**Comment by nedhyett** [comment]
Does the issue still take place if you disable Vermilion?

**Comment by nedhyett** [comment]
Also, what do you get if you type

```
lua_run print(VERSIONSTR)
```

Into the server console?

**Comment by nedhyett** [comment]
I know this sounds a bit mean, but I need to get this resolved. If I don't get a response in, let's say, 5 days, I'm going to mark this as closed. Again, not meaning to be rude, I just want to get this sorted out ASAP.

**Comment by TwistedTail** [comment]
Sorry for not responding this. I had to re-make the server so I lost all the info to fix the problem.
Completely my fault. If it happens again I'll give you all the necesary information instead of just erasing the server.

**Comment by nedhyett** [comment]
Sure thing. I'm still pretty sure that it wasn't a Vermilion problem, since I don't do server version checking that kicks players (I just print a warning).
