### ISSUE TITLE
Unable to create graffiti's?

### ISSUE THREAD

**Issue by TwistedTail** [nedhyett/Vermilion#115]
No console logs, no visual proof.

All the users have the permission to create them, also they're allowed in the "Basic Settings" section.

Even the owner of the server, actually me, can't create them.

**Comment by nedhyett** [comment]
Does it work if you disable the spray control inside the Basic Settings tab?

**Comment by TwistedTail** [comment]
Yes, it works.

**Comment by nedhyett** [comment]
You probably need to assign permissions for it, then.
