### ISSUE TITLE
Error Occurs When trying to set ranks

### ISSUE THREAD

**Issue by ickycoolboy** [nedhyett/Vermilion#125]
[ERROR] addons/vermilion2/lua/vermilion2/modules/rank_editor/init.lua:1064: attempt to index field 'Rank' (a nil value)
  1. onClick - addons/vermilion2/lua/vermilion2/modules/rank_editor/init.lua:1064
   2. DoClick - addons/vermilion2/lua/vtoolkit/gui.lua:292
    3. unknown - lua/vgui/dlabel.lua:218

The rank will not change when this error occurs so I can currently not change any ranks
(I was the only one on the server at the time testing so i was trying to derank myself from owner to player)

**Comment by nedhyett** [comment]
Oops. This is a reminant from when I replaced the clientside API. Thanks for pointing it out. Fixing now.
