### ISSUE TITLE
Addons not understanding Admin rights

### ISSUE THREAD

**Issue by atsivertes** [nedhyett/Vermilion#134]
Basically i switched to the github version to fix the No fall damage issue, but now whenever i set myself to owner or admin, other addons say that iam not admin and i cant configure them anymore.

Going back to workshop fixes this but then there is No fall damage.
Gmod version 2015.06.01

**Comment by nedhyett** [comment]
What addons are not being recognised? I'm going to need a list. I changed the way the entire backend works for Vermilion in this version, so I expect it's something to do with that, but to figure it out, I need to know what the problem addon(s) is/are.

**Comment by atsivertes** [comment]
every single item i have in my collection http://steamcommunity.com/sharedfiles/filedetails/?id=464780730

the only exception is that the Admin tab in the Utilities, but thats not an addon so iam not sure.

**Comment by nedhyett** [comment]
I have had issues with CAP in the past. It doesn't always do what I expect it to, for example, if I remember this correctly, it uses a strange way of spawning entities that circumvents normal methods, so I had to add specific code to catch CAP entities. I'll have to have a look at how it checks for permissions.

I'm thinking about proposing/developing a common interface for checking permissions. Sort of like CPPI, but for general management.

The way that Vermilion communicates permissions to other mods is a bit hacky at the moment, to say the least. Basically it overrides the vanilla users text file (the file that you put a SteamID into to assign ranks) and uses the identify_as_admin and identify_as_superadmin to determine what value to report to other mods.

Note to self: fix the NWVar that determines the usergroup so it reports the correct value when the identify_as_x permissions are in use.
