### ISSUE TITLE
[Proposal] Check and kick missing addons/collection

### ISSUE THREAD

**Issue by atsivertes** [nedhyett/Vermilion#135]
Basically i dont know if this is possible to do, but it would be really nice to have this feature, iam not sure if the bug still exists where when you download from workshop while connecting to the server and when u join theres issues with models and textures for addons, i usually tell people to sub to a collection before joining.

Basically when the player starts joining the server, vermilion would check missing workshop addons, and deny the player from joining with a reason saying(make it customisable maybe?):

You are missing addons, please subscribe to our server collection, to be able to play without any issues. http://steamcommunity.com/sharedfiles/filedetails/?id=xxxxxxxxxx

It would be really good for servers that run lots and lots of addons, for the past few days of starting my server i saw loads of people just stoping in the middle while downloading addons.

**Comment by nedhyett** [comment]
Issues #72 #73 #74 already cover this.

**Comment by nedhyett** [comment]
I'll still add it, I just want to keep the issues page tidy, so don't get annoyed if I flag and close duplicate issues.

**Comment by atsivertes** [comment]
I feel like an asshole for not checking other issues....
googled this for a while, but missed this.......
Sorry

**Comment by nedhyett** [comment]
No worries, we all do that at some point.
