### ISSUE TITLE
Vermilion 2 not working

### ISSUE THREAD

**Issue by ShadowChaos** [nedhyett/Vermilion#148]
I attempted to open the menu and it said I had a script error

Entire console input that game:
Adding Filesystem Addon 'c:\program files (x86)\steam\steamapps\common\garrysmod\garrysmod\addons\half-life_2_content_pack'
Initializing Awesomium..
No Kinect SDK
Unknown command "has_dyntagging"
Unknown command "has_lasttrail"
Unknown command "has_envdmgallowed"
Unknown command "has_maxrounds"
Unknown command "has_choosetype"
Unknown command "has_timelimit"
Unknown command "has_minplayers"
Unknown command "has_infinitestamina"
Unknown command "has_seekoncaught"
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Changing gamemode to Trouble in Terrorist Town (terrortown)
Not playing a local game.
Addons have changes - remounting
Changing gamemode to Prop Hunt (prop_hunt)
Network: IP Not important, mode MP, dedicated No, ports 27015 SV / 27005 CL
PREP OK
Weapon Strip con var created
Penetration/ricochet con var created
Recoil con var created
Ammo crate detonation con var created
Damage Multiplier con var created
Default Clip con var created
Unique Slots con var created
[Vermilion2 - Server] Starting up...
[Vermilion2 - Server] Loading skin: basic.lua
[Vermilion2 - Server] Compiling language file: vermilion2/lang/de.lua
[Vermilion2 - Server] Compiling language file: vermilion2/lang/en.lua
[Vermilion2 - Server] Compiling language file: vermilion2/lang/ru.lua
[Vermilion2 - Server] Registered driver "Data"!
[Vermilion2 - Server] Backing up configuration file...

[Vermilion 2] lua/vermilion2/config/drivers/data/driver_sh.lua:144: attempt to index field 'Data' (a nil value)
  1. Load - lua/vermilion2/config/drivers/data/driver_sh.lua:144
   2. LoadConfiguration - lua/vermilion2/config/sv_config.lua:179
    3. unknown - lua/vermilion2/config/sv_config.lua:182
     4. include - [C]:-1
      5. unknown - lua/autorun/vermilion_autorun.lua:206

[Vermilion 2] lua/vermilion2/config/drivers/data/driver_sh.lua:34: attempt to index field 'Data' (a nil value)
  1. GetData - lua/vermilion2/config/drivers/data/driver_sh.lua:34
   2. unknown - lua/vermilion2/geoip.lua:72
    3. include - [C]:-1
     4. unknown - lua/autorun/vermilion_autorun.lua:206

[Vermilion 2] lua/vermilion2/config/drivers/data/driver_sh.lua:34: attempt to index field 'Data' (a nil value)
  1. GetData - lua/vermilion2/config/drivers/data/driver_sh.lua:34
   2. unknown - lua/vermilion2/targetid.lua:39
    3. include - [C]:-1
     4. unknown - lua/autorun/vermilion_autorun.lua:206

[Vermilion2 - Server] Loading modules...
[Vermilion2 - Server] Error loading module: lua/vermilion2/config/drivers/data/driver_sh.lua:34: attempt to index field 'Data' (a nil value)

Trace: 
	1: Line 32	"Trace"	lua/includes/extensions/debug.lua
	2: Line 162	"__index"	lua/vermilion2/shared.lua
	3: Line 34	"GetActiveLanguage"	lua/vermilion2/config/drivers/data/driver_sh.lua
	4: Line 89	"TranslateStr"	lua/vermilion2/shared.lua
	5: Line 132	"TranslateStr"	lua/vermilion2/core/basemodule.lua
	6: Line 31	"nil"	lua/vermilion2/modules/client_settings/init.lua
7	C function
	8: Line 160	"LoadModules"	lua/vermilion2/shared.lua
	9: Line 211	"nil"	lua/autorun/vermilion_autorun.lua

[Vermilion2 - Server] Error loading module: lua/vermilion2/config/drivers/data/driver_sh.lua:34: attempt to index field 'Data' (a nil value)

Trace: 
	1: Line 32	"Trace"	lua/includes/extensions/debug.lua
	2: Line 162	"__index"	lua/vermilion2/shared.lua
	3: Line 34	"GetActiveLanguage"	lua/vermilion2/config/drivers/data/driver_sh.lua
	4: Line 89	"TranslateStr"	lua/vermilion2/shared.lua
	5: Line 132	"TranslateStr"	lua/vermilion2/core/basemodule.lua
	6: Line 125	"nil"	lua/vermilion2/modules/server_settings/init.lua
7	C function
	8: Line 160	"LoadModules"	lua/vermilion2/shared.lua
	9: Line 211	"nil"	lua/autorun/vermilion_autorun.lua

[Vermilion 2] lua/vermilion2/config/drivers/data/driver_sh.lua:34: attempt to index field 'Data' (a nil value)
  1. GetData - lua/vermilion2/config/drivers/data/driver_sh.lua:34
   2. LoadModules - lua/vermilion2/shared.lua:171
    3. unknown - lua/autorun/vermilion_autorun.lua:211

0
butterfly activated
jet pack activated
Default clips will be not be modified
[AddCSLuaFile] Couldn't find 'weapons/gmod_tool/shared.lua' (<nowhere>)
...
SWEP (weapon_ttt_slam) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_ttt_defib) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_ttt_awp) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (molotov_cocktail) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_bfg_csgo_zeusx27) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
ERROR: Trying to derive entity bl15_sent_bomb from non existant entity base_gmodentity!
ERROR: Trying to derive entity cod-c4 from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_chute from non existant entity base_gmodentity!
game.ConsoleCommand blocked! (mp_flashlight)
Making workshop gamemode available for client download
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg/mapcycle.txt' was not found.)
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type info_ladder!
Can't init info_ladder
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_hostage_rescue!
Can't init func_hostage_rescue

[L] Prop Hunt
Map: cs_assault
Players: 1 / 4
Build: 6058
Server Number: 1

Garry's Mod

prop_hunt
cs_assault
4
76561198144446593
Requesting 1 lua files from the server
GetPublishedFileDetails failed!
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: de_train/blendgraveldirt001a). This wastes perf for no benefit.
clientside lua startup!
--- Missing Vgui material vgui/hud/test_rifle
Client-side Gas Effect Con Var created
[Vermilion2 - Client] Starting up...
[Vermilion2 - Client] Loading skin: basic.lua
[Vermilion2 - Client] Compiling language file: vermilion2/lang/de.lua
[Vermilion2 - Client] Compiling language file: vermilion2/lang/en.lua
[Vermilion2 - Client] Compiling language file: vermilion2/lang/ru.lua
[Vermilion2 - Client] Registered driver "Data"!
[Vermilion2 - Client] Started in 0.094ms triggering 18 files.
Requesting texture value from var "$dummyvar" which is not a texture value (material: NULL material)
Reloaded Control: VoiceNotify
butterfly activated
jet pack activated
Default clips will be not be modified
...
--- Missing Vgui material sprites/scope
SWEP (weapon_ttt_slam) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_ttt_defib) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_ttt_awp) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (molotov_cocktail) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
SWEP (weapon_bfg_csgo_zeusx27) is derived from non existant SWEP (weapon_tttbase) - Expect errors!
ERROR: Trying to derive entity bl15_sent_bomb from non existant entity base_gmodentity!
ERROR: Trying to derive entity cod-c4 from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_chute from non existant entity base_gmodentity!

[Vermilion 2] lua/vermilion2/config/drivers/data/driver_sh.lua:271: attempt to index field 'Data' (a nil value)
  1. GetUser - lua/vermilion2/config/drivers/data/driver_sh.lua:271
   2. hookFunc - lua/vermilion2/shared.lua:268
    3. unknown - lua/vermilion2/core/hooks.lua:87

VToolkit: Synced the client time with the server.
Compact freed 638976 bytes
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Redownloading all lightmaps
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_hostage_rescue!
Can't init func_hostage_rescue
Ragnorak suicided!
Ragnorak joined Props
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type hostage_entity!
Can't init hostage_entity
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_buyzone!
Can't init func_buyzone
Attempted to create unknown entity type func_hostage_rescue!
Can't init func_hostage_rescue
Teams have been swapped!
VToolkit: Synced the client time with the server.
[Vermilion2 - Client] Warning: you have made a spelling error in the 'vermilion_menu' command. Please re-bind the command!
[Vermilion2 - Client] There was an error during startup and the menu did not get built. Please look for stack traces and report them ASAP.

[Vermilion 2] lua/vermilion2/menuclient.lua:1066: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1066
   2. unknown - lua/includes/modules/concommand.lua:54

[Ragnorak|2|STEAM_0:1:92090432] Lua Error:

[Vermilion 2] lua/vermilion2/menuclient.lua:1066: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1066
   2. unknown - lua/includes/modules/concommand.lua:54

] bind "/" vermilion_menu
[Vermilion2 - Client] There was an error during startup and the menu did not get built. Please look for stack traces and report them ASAP.

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

[Ragnorak|2|STEAM_0:1:92090432] Lua Error:

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

] vermilion_menu "/"
[Vermilion2 - Client] There was an error during startup and the menu did not get built. Please look for stack traces and report them ASAP.

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

[Ragnorak|2|STEAM_0:1:92090432] Lua Error:

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

[Vermilion2 - Client] There was an error during startup and the menu did not get built. Please look for stack traces and report them ASAP.

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

[Ragnorak|2|STEAM_0:1:92090432] Lua Error:

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

] vermilion_menu
[Vermilion2 - Client] There was an error during startup and the menu did not get built. Please look for stack traces and report them ASAP.

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

[Ragnorak|2|STEAM_0:1:92090432] Lua Error:

[Vermilion 2] lua/vermilion2/menuclient.lua:1058: attempt to call method 'Open' (a nil value)
  1. unknown - lua/vermilion2/menuclient.lua:1058
   2. unknown - lua/includes/modules/concommand.lua:54

I was on cs_assault (it was working on here earlier on prop hunt and ttt but I closed gmod, came back and this happened, already tried un-installing and re-installing) to my knowledge I have no map managers

It was a private himachi based server

version number 2015.06.28

It worked perfectly earlier when I tested it by myself (same settings and an online game just no one else in it) I left gmod and came back an hour later to play with friends and I got the error message during the loading screen and every time I tried to open the menu.

**Comment by nedhyett** [comment]
That looks like a corrupted configuration file to me... try shutting down the server, removing the configuration file in the data directory (vermilion2 folder) and starting the server again. I really need to figure out what is causing the problem... According to my notes, this will be the 9th time I have tried to fix this exact problem. It went away for so long, and now it's back, this time, with an apparent vengance. I have been given a configuration file that is causing this problem already. I am running a bit low on time at the moment. I'll see what I can do to fix them problem permanently.

Also, the map management thing in the description is an example. You don't need to tell me about maps unless you think it's important. Although it is reassuring to know that at least someone is reading the description...

**Comment by ShadowChaos** [comment]
It was a corrupt config file, and by that I mean I couldn't even open the
file to have a peek. Thank you very much for your help in this and I look
forward to using (and maybe abusing) your programme with my friends =3
If there is anyway that I can help fix this, whether it be by sending logs,
or copies of whatever files, I would be more then happy to oblige c:
Wishing you all the best
Josh

**Comment by nedhyett** [comment]
The configuration file looks like that anyway. It's compressed to prevent meddling-related bugs. It also makes it impossible for me to ask people to just edit the configuration file instead of using a GUI. I already have a "corrupt" configuration file available to me, I just need to get some free time to load it up.

**Comment by ShadowChaos** [comment]
Not all the symbols and stuff, it was literally un-openable at all until I
deleted it and restarted gmod.
Just wasn't sure if that was the same issue or a separate matter :3
