### ISSUE TITLE
Vermilion breaks DarkRP

### ISSUE THREAD

**Issue by nedhyett** [nedhyett/Vermilion#183]
- [ ] Jobs are lost
- [ ] Money is lost
- [ ] No salary
- [ ] Props have no owner
- [ ] Map spawn is broken
- [ ] No weapon spawning for owner
- [ ] Bad texture

**Comment by frostfgn** [comment]
a lot of this is actually caused by darkrp not being able to connect to it's database. i've ran vermilion on darkrp with no issues. :+1:

**Comment by nedhyett** [comment]
Fair enough. It looks like I'll close this then, since I've been able to run DarkRP in the past with Vermilion fine too.
