### ISSUE TITLE
Various text related bugs

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#186]
- All text boxes' text is invisible
- In the autobroadcast editing screen, the text box expands and covers the color selection box

**Comment by nedhyett** [comment]
I'm pretty sure this would replicate throughout all of Vermilion, since the text boxes are all spawned from the same function. I'll start fixing that now.

**Comment by nedhyett** [comment]
I've pushed a change to the skinning system that appeared to fix the bug on my system (however, I'm not sure how or why it was fixed). If it persists, please re-open the issue with more details.
