### ISSUE TITLE
Allow banning of players whilst player is not online.

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#190]
Allow the banning of a player whilst the player is not online. There have been multiple occasions where I cannot ban someone who gets off of the server before I can ban them, and this leads to people who were supposed to be banned not being banned and coming back at a later time.

**Comment by nedhyett** [comment]
If you can get hold of their SteamID, the ban command in the chat can use it to force a ban into the system when players are not online.

**Comment by frdyttedf1** [comment]
Ah, I see. Well, the userdata browser records steam IDs so that shouldn't be an issue. Thank you!
