### ISSUE TITLE
Vermilion console commands

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#191]
I'm trying to create a command menu for my players to make it easier for them to execute commands and use their abilities to the full extent possible. As most of the server commands come from vermilion, I was wondering if there are console commands for the chat commands for vermilion? Or, would making the command menu make the player run the "say !<command>" command produce the same output as typing it in in the chat box? Thank you.

**Comment by nedhyett** [comment]
The "vermilion" console command mirrors every chat command. Just replace the "!" with "vermilion " in the console, and it should do the same as if it were typed in chat.
