### ISSUE TITLE
Special character grouping 

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#193]
As a lot of people love to styleize their names, often vermilion will not be able to target that player in commands. For example, if you have a player on a server, named 'ÅBČ', if you were to type 'ABC' into the field to target said person, it wouldn't be able to target them. And there are even more styalized characters that aren't used commonly (like the accent circumflex over the 'č' in French) that it will not target whatsoever. It seems to already do a little bit of grouping but many characters seem to not work.

**Comment by nedhyett** [comment]
I don't understand what you mean? Are you saying that it ignores users who have these characters (they don't appear in the chat predictor at all) or that they appear but the command rejects them as a valid player?

**Comment by frdyttedf1** [comment]
As in, in order to highlight their name in certain commands, you need to type the special character that their name starts with (which sometimes is like a heart symbol or something that you have to memorize the character codes for) which makes it difficult. I'll do a little bit of testing on my server right now, but this is what I've seen so far.

**Comment by nedhyett** [comment]
You should be able to highlight their name using the chat predictor (up and down keys) and then press tab to insert it into chat. Does that work?

**Comment by frdyttedf1** [comment]
Nevermind, I suppose something happened. It's all good now, working perfectly fine. Seriously, thank you for your quick responses.

**Comment by nedhyett** [comment]
Not a problem. I have time, and I get notified at least 3 times whenever something happens here. It's hard to miss.
