### ISSUE TITLE
Selective "name" field in commands

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#194]
Names with spaces often don't allow you to target players in commands with more then one argument. For example, say you have a player named 'ABC' and a player named 'A BC'. If you try to target ABC in the '!noclip ABC 0' command, it would have no issue whatsoever. But, if you tried to target A BC in the command '!noclip A BC 0', it would try to find a player with the name of 'A' and give its noclip value a value of 'BC' (and the zero would be ignored.) Either this is the issue, or the command is trying to target the players name as 'A BC 0'. If we could have some sort of field to select players with spaces in their names, E.G. '!noclip ""A BC"" 0', that would be wonderful.

**Comment by frdyttedf1** [comment]
Sorry that I'm submitting so many ideas and bugs and things, I just have a lot of ideas and would love to see some of them implimented/help you improve your already wonderful addon.

**Comment by nedhyett** [comment]
Quote it. "I have a username with spaces" will target that user.

**Comment by frdyttedf1** [comment]
Oh, alrighty. Thank you!
