### ISSUE TITLE
Jail Escaping Glitch

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#202]
It's easier just to send you a video then explain it through text. If you noclip in strange ways quickly it lets you free. https://drive.google.com/open?id=0B0Y2iDYXQg_LVEJiNHA4ZEh1RzA

**Comment by nedhyett** [comment]
I am unable to reproduce this glitch. Are you using the workshop or repository version?

**Comment by frdyttedf1** [comment]
Workshop.

**Comment by nedhyett** [comment]
Apologies for the delay, a lot of things have been going on recently.

That probably explains it, then. The workshop version is using an old algorithm for detecting jail entry and exit which miscalculates the position of players within the zone. The repository version replaces this with a standard calculation that works both ways. Hopefully that is the reason I can't reproduce this.
