### ISSUE TITLE
broken with darkrp

### ISSUE THREAD

**Issue by formatme** [nedhyett/Vermilion#38]
[ERROR] addons/vermilion2/lua/vermilion2/config.lua:437: attempt to concatenate local 'permission' (a nil value)
  1. HasPermission - addons/vermilion2/lua/vermilion2/config.lua:437
   2. GetUserGroup - addons/vermilion2/lua/vermilion2/modules/rank_editor/init.lua:171
    3. IsAdmin - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sh_shared.lua:54
     4. calculateCanTouchForType - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:84
      5. calculateCanTouch - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:159
       6. onEntitiesCreated - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:328
        7. unknown - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:343

Timer Failed! [FPP_OnEntityCreatedTimer][@gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua (line 351)]

[ERROR] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:7: attempt to perform arithmetic on a nil value
  1. addMoney - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:7
   2. callback - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:33
    3. retrieveSalary - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:278
     4. payDay - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:25
      5. unknown - gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua:157

Timer Failed! [928459425jobtimer][@gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua (line 155)]

**Comment by nedhyett** [comment]
I assume this if no longer a problem since I can run Vermilion and DarkRP with no errors on my test server.
