### ISSUE TITLE
votes

### ISSUE THREAD

**Issue by Spennyone** [nedhyett/Vermilion#40]
votes for kicking,banning, or even votings for allowed Server CVars? (Like sv_gravity for example)

**Comment by nedhyett** [comment]
There is a voting system in the original version of Vermilion, however to add this to the Vermilion 2, it would require adding a new feature I call "active notifications" (notifications that require user input before they are dismissed). I'll look into this tomorrow, when I have time.

**Comment by nedhyett** [comment]
Added.
