### ISSUE TITLE
Ownership problem when looking at a entity

### ISSUE THREAD

**Issue by Kro55f1r3** [nedhyett/Vermilion#46]
**A description of what you were doing that caused the error**

When looking at a entity i had spawned on the map.

**A copy of the error(s) from the console**

[Vermilion 2] lua/includes/util.lua:173: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:173
   2. entGetTouchReason - gamemodes/darkrp/gamemode/modules/fpp/pp/client/ownability.lua:80
    3. v - gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:159
     4. oldHook - lua/includes/modules/hook.lua:84
      5. unknown - lua/vermilion2/shared.lua:219

**A list of addons that could have interfered with the operation (i.e. if the map manager broke, what map were you on, what map did you try load and do you have any other map management addons installed?)**

Map RP_Saintlouis + Workshop Addons : 401281390 (Vermilion removed to continue to work on my server)

**Was the server dedicated or not? (optional)**

It's a dedicated server.
 
**Anything else you feel would be helpful. If you don't provide something that I need to solve the problem that isn't listed here, I'll let you know on a case-by-case basis.**

That's problem occuring also on ULX about rebuild hook (with priority problem)
That's making some conflict when you got a DarkRP with a lot content

**Comment by nedhyett** [comment]
I am aware of this type of error. This is a problem that is caused by a bad interaction between Vermilion's prop-protection module and FPP (they are doing the same thing and conflicting with each other). However, that looks to me like it's an error with FPP itself and since Vermilion overwrites the hook system, it's getting blamed... again...

**Comment by nedhyett** [comment]
No response for over 2 months. I'm going to assume that this isn't a problem anymore as nobody else has reported it.
