### ISSUE TITLE
Error while removing mode from zone

### ISSUE THREAD

**Issue by knackrack615** [nedhyett/Vermilion#47]
A description of what you were doing that caused the error

Added mode "Anti-Noclip" on a zone and after removed it

Now i can no longer add modes

A copy of the error(s) from the console

[ERROR] addons/vermilion2/lua/vermilion2/modules/zones/init.lua:588: attempt to index local 'zone' (a nil value)
  1. unknown - addons/vermilion2/lua/vermilion2/modules/zones/init.lua:588
   2. DistributeEvent - addons/vermilion2/lua/vermilion2/modules/zones/init.lua:191
    3. Call - addons/vermilion2/lua/vermilion2/shared.lua:201
     4. RemoveMode - addons/vermilion2/lua/vermilion2/modules/zones/init.lua:85
      5. unknown - addons/vermilion2/lua/vermilion2/modules/zones/init.lua:707
       6. DidGetNetStr - addons/vermilion2/lua/vermilion2/shared.lua:447
        7. func - addons/vermilion2/lua/vermilion2/shared.lua:514
         8. unknown - lua/includes/modules/net.lua:32

A list of addons that could have interfered with the operation (i.e. if the map manager broke, what map were you on, what map did you try load and do you have any other map management addons installed?)

Nothing

Was the server dedicated or not? (optional)

It's a dedicated server running on ubuntu 14.04.

Anything else you feel would be helpful. If you don't provide something that I need to solve the problem that isn't listed here, I'll let you know on a case-by-case basis.

Nothing

**Comment by nedhyett** [comment]
I'll look into the problem. It's probably to do with the recent overhaul of the zone properties system, however a fix won't be available for a while since I'm overhauling nearly every pare of Vermilion's core and that's going to take time. I'll make sure I fix it before the next update though.

**Comment by nedhyett** [comment]
Fixed. Caused by a zone not referring to itself as "self" inside the RemoveMode function. Fix will be published with version 2.5.
